### ISSUE TITLE
java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by Denniszz** [TinkoffCreditSystems/gatling-amqp-plugin#3]
Hello,
I hope you can assist. I tried to use your plugin. But I always see the error: 

11:27:15.464 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.IncompatibleClassChangeError: Implementing class

can you assist?

I will add my pom and my simulation file and complete maven output.

thanks in advance

[complete maven output.txt](https://github.com/TinkoffCreditSystems/gatling-amqp-plugin/files/3706863/complete.maven.output.txt)
[pom.xml.txt](https://github.com/TinkoffCreditSystems/gatling-amqp-plugin/files/3706868/pom.xml.txt)

[TestAMQPplugin.scala.txt](https://github.com/TinkoffCreditSystems/gatling-amqp-plugin/files/3706893/TestAMQPplugin.scala.txt)

**Comment by red-bashmak** [comment]
Hello,
I advise you to use sbt with the official gatling plugin, because the plugin was tested only with sbt. Sbt is more friendly to scala-projects and to gatling-scenarios as well.

**Comment by red-bashmak** [comment]
You can try using Gatling version 3.1.x (<gatling.version>3.1.3</gatling.version>). Because in 3.2.x the api of checks has changed, so apparently the classloader does not find something. Support for 3.2.x version of gatling was added in last commit in master branch, but new version of plugin is not ready yet. You can clone this repository and build plugin localy with command sbt publishLocal. Or soon new version of plugin are added in maven, and you can use this new version.

**Comment by Denniszz** [comment]
Thank you very much.
Using Gatling version 3.1.3 works fine!
I will close this issue
